version: '3.2'

services:
  db:
    image: mysql:8.0
    container_name: bigdev_mysql
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: bigdevbot
      MYSQL_USER: bigdev
      MYSQL_PASSWORD: bigdevsecret
      MYSQL_ROOT_PASSWORD: bigdevsecret

  app:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: bigdev_phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
